//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 由 QuickPowerAction.rc 使用
//
#define IDR_MAINFRAME					128
#define IDM_ABOUTBOX					0x0010
#define IDD_ABOUTBOX					100
#define IDS_ABOUTBOX					101
#define IDD_QUICKPOWERACTION_DIALOG				102

// 电源操作单选按钮
#define IDC_RADIO_SHUTDOWN				1001
#define IDC_RADIO_REBOOT				1002
#define IDC_RADIO_LOCK					1003
#define IDC_RADIO_LOGOFF				1004
#define IDC_RADIO_SLEEP					1005
#define IDC_RADIO_HIBERNATE				1006

// 其他控件
#define IDC_COMBO_SLEEP_MODE			1010
#define IDC_CHECK_FORCE				1011
#define IDC_BTN_EXECUTE				1012
#define IDC_STATIC_POWER_ACTION		1013
#define IDC_STATIC_SLEEP_MODE			1014

// 新对象的下一组默认值
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	129
#define _APS_NEXT_CONTROL_VALUE		1015
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
