name: Unit Tests

on:
  push:
    branches:
      - '*/*'
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MFC
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`) do (
            set VS_PATH=%%i
          )

          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\setup.exe" modify ^
          --installPath "%VS_PATH%" ^
          --add Microsoft.VisualStudio.Workload.NativeDesktop ^
          --add Microsoft.VisualStudio.Component.VC.ATLMFC ^
          --includeRecommended ^
          --passive --norestart

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore QuickPowerAction.sln

      - name: Build Test Configuration
        run: msbuild QuickPowerAction.sln /p:Configuration=Test /p:Platform="${{ matrix.platform }}" /m /verbosity:minimal

      - name: Run Unit Tests
        run: |
          $exePath = "Build\${{ matrix.platform }}\Test\QuickPowerAction.exe"
          Write-Host "Running tests from: $exePath"
          & $exePath